version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      -  ./data:/data/db
    ports:
      - "27017:27017"
  # app:
  #   container_name: 
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:8080
  #   external_links:
  #     - mongo
  #   depends_on:
  #     - mongo