version: '3.8'
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      -  ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - employee-network
  app:
    container_name: employee-backend
    restart: always
    build:
      context: .
    depends_on:
    - mongo
    ports:
      - 8080:8080
    external_links:
      - mongo
    networks:
      - employee-network
    volumes:
      - ./:/usr/src/app 
      - /usr/src/app/node_modules


networks:
  employee-network:
    external: true 